Connection handler
ECE-IoT/esp-iot-framework pull request #11
Opened 2022-02-09 21:53 UTC by Soelsdan

Ich hab jetzt mal bis auf den connection handler einen ersten Schuss für die Klassen Doku fertig. Für die Core Doku hab ich mir eine initiale Struktur überlegt.

Das Ganze ist definitv nicht ganz fertig und wir sollten die Struktur noch durchdiskutieren, aber ich habe jetzt den Pull request erstellt, dammit jeder in seiner Doku für weitere Erklärungen auf meine .md files verlinken kann.

2022-02-10 13:36 UTC, t3mschm2d commented on docs/core/core_classes/esp_config.md
> +To create the configuration file the python script genreate_config.py is used. This script must be called from a command line, and the settings are then entered from the command line as well. Then a
Wenn du file-namens, "inline" code Zeilen oder andere programmier-Begriffe hast verwende bitte `begriff`. Die `` geben deinem Begriff dann eine besondere Hervorhebung welche es einfacher macht wichtige Namen gut erkennen zu können!

2022-02-10 13:49 UTC, t3mschm2d requested changes
Prinzipiell gut. Es fehlt natürlich noch einiges. Gerade z.B. der `connection_handler`.

Ich würde dich darüber hinaus bitten, dass du schaust gerade "Programmier-Relevante" Punkte hervor zu heben. Wie bereits angemerkt klappt das gut mit ``.

2022-02-10 13:49 UTC, t3mschm2d commented on docs/core/core_classes/esp_config.md
> +To create the configuration file the python script genreate_config.py is used. This script must be called from a command line, and the settings are then entered from the command line as well. Then a
Wenn du file-namens, "inline" code Zeilen oder andere programmier-Begriffe hast verwende bitte `begriff`. Die `` geben deinem Begriff dann eine besondere Hervorhebung welche es einfacher macht wichtige Namen gut erkennen zu können!

2022-02-10 13:49 UTC, t3mschm2d commented on docs/core/core_classes/esp_config.md
> +To read the config file you have to call only once the readConfig() function of the EspConfig object.
Bitte wieder `` für readConfig() verwenden -> `readConfig()`

2022-02-10 13:49 UTC, t3mschm2d commented on docs/core/core_classes/esp_config.md
> +To read the config file you have to call only once the readConfig() function of the EspConfig object.
Bzw. auch für `EspConfig`

2022-02-10 13:49 UTC, t3mschm2d commented on docs/core/core_classes/esp_config.md
> +The Esp_Config class is used on the ESP to read the configuration file from SPIFFS and to make the its contents available through get....() functions.
`EspConfig` und `getFkt()` (als Platzhalter für Getter Funktionen)

2022-02-10 13:49 UTC, t3mschm2d commented on docs/core/core_classes/esp_keys.md
> +1. Privat Key (/esp32-d1mini-01.private.key)
Jeweils bitt wieder mit `esp32-d1mini-01.private.key` verwenden

2022-02-10 13:49 UTC, t3mschm2d commented on docs/core/core_classes/esp_keys.md
> +You get these files from AWS and the process is described here (TODO Tims beschreibung einfügen)
Hier kannst du dann einfach einen Link zu dem was ich für AWS beschreibe einfügen!

2022-02-10 13:49 UTC, t3mschm2d commented on docs/core/core_classes/esp_keys.md
> +The purpose of this class is to read the three files from the file system and make them accessible by get...() functions. The files are read by calling the begin() function of the class.
`getFkt()`

2022-02-10 13:49 UTC, t3mschm2d commented on docs/core/core_classes/esp_logger.md
> +1. LOG_LEVEL_OFF
Jeweils wieder `LOG_LEVEL_OFF` usw...

2022-02-10 13:49 UTC, t3mschm2d commented on docs/core/core_classes/esp_spiffs.md
> +![folder image](./../../assets/upload_spiffs.png)
Das Bild hat einen falschen Pfad! Es wird nicht angezeigt!

2022-02-10 13:52 UTC, t3mschm2d commented
Eine weitere Anmerkungen: Es sind zwar jetzt einige Kommentare in deinem Code die vor allem die "Hervorhebungen" ansprechen. Das sind natürlich nicht alle Punkte die hervor gehoben werden können!

Die Struktur und der grundsätzliche Aufbau ist aber wirklich gut

2022-02-10 14:02 UTC, merged

2022-02-11 09:35 UTC, Soelsdan commented on docs/core/core_classes/esp_keys.md
> +You get these files from AWS and the process is described here (TODO Tims beschreibung einfügen)
Das war mein Plan